### ISSUE TITLE
ExpandableListView 貌似不起作用

### ISSUE THREAD

**Issue by xingag** [miomin/SHSwipeRefreshLayout#1]
ExpandableListView 貌似不起作用，上拉刷新和下拉加载都没有效果

**Comment by miomin** [comment]
感谢反馈，我会尽快适配。

**Comment by miomin** [comment]
目前滑动冲突没有想到在Swipe中解决的办法，暂时解决办法：ExpandableListView实现NestedScrollingChild接口即可，参考[ShareScrollView](https://github.com/miomin/SHSwipeRefreshLayout/blob/master/shswiperefresh/src/main/java/com/scu/miomin/shswiperefresh/view/ShareScrollView.java)
