### ISSUE TITLE
换成listview等其他view怎么不能下拉刷新了呢

### ISSUE THREAD

**Issue by yongming9011** [miomin/SHSwipeRefreshLayout#3]

**Comment by miomin** [comment]
暂时只支持RecyclerView和ScrollView，使用ScrollView需要使用我提供的ShareScrollView，如果要ListView可以模仿ShareScrollView的实现自己扩展一下，这里涉及到嵌套滚动，还没想到在Swipe中解决的办法，暂时先这么解决吧

**Comment by miomin** [comment]
ListView实现一下NestedScrollingChild接口就能用了。参考 [ShareScrollView](https://github.com/miomin/SHSwipeRefreshLayout/blob/master/shswiperefresh/src/main/java/com/scu/miomin/shswiperefresh/view/ShareScrollView.java)

**Comment by miomin** [comment]
请依赖v1.3.0或最新版本，使用SHListView即可正常使用

**Comment by yongming9011** [comment]
@miomin 👍👍👍
